version: "3.1"
services:
  flask:
    build: ./backend
    image: flask
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./src/assests/images/:/src/assests/images/

  react:
    build: ./
    image: react
    container_name: reacts
    ports:
      - "80:3000"