version: "3.1"
services:
  flask:
    build: ./backend
    image: flask
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
      # - ./backend:/app
      - shared-folder:/src/assests/plots

  react:
    build: ./
    image: react
    container_name: react
    ports:
      - "80:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - shared-folder:/app/src/assests/plots

volumes:
  shared-folder: