version: '3.1'
services:
    backend:
        build: ./backend
        ports:
            - "5000:5000"
        volumes: 
            - ./backend:/app
            - ./src/assests/images/:/src/assests/images/
    frontend:
        build: ./
        ports:
            - "3000:3000"
